### ISSUE TITLE
Поддержать свойства appendTo и/или class в error у блока input

### ISSUE THREAD

**Issue by glukki** [yandex-ui/nanoislands#467]
Речь вот о таком:
```
nb-input({
    'name': 'city'
    'error': {
        'content': 'some error'

        'appendTo': 'whatever'
        'class': 'whatever'
    }
})
```

Необходимость возникла в случае, когда надо показывать попап ошибки для инпута, находящегося в попапе с вручную выставленным `z-index: 10000` (больше, чем z-index по умолчанию у попапа)

**Comment by basvasilich** [comment]
добавил класс
