### ISSUE TITLE
Возможность ограничивать высоту попапа

### ISSUE THREAD

**Issue by JhonyLe** [yandex-ui/nanoislands#470]
Нужны следующие дополнительный возможности для попапа:
- возможность задать максимальную высоту;
- возможность задать отступ от нижней границы экрана так, чтобы попап не опускался ниже этой границы и менял высоту при ресайзе окна, так чтобы граница не менялась.

**Comment by basvasilich** [comment]
`возможность задать максимальную высоту;`
сделал

Второе кажется странным.
