### ISSUE TITLE
Некорректно выставляется класс на обёртку попапа

### ISSUE THREAD

**Issue by i2r** [yandex-ui/nanoislands#496]
1) В методе ``_create`` (https://github.com/yandex-ui/nanoislands/blob/master/blocks/popup/popup.js#L112-L117) мы вычисляем с помощью функции ``_getUIDialogExtraClass`` класс и сохраняем в ``options.dialogClass`` виджета. Сразу после создания попап открывается с корректно выставленным классом. Но, при повторном открытии, мы затираем вычисленный класс в методе ``_move`` наноблока: https://github.com/yandex-ui/nanoislands/blob/master/blocks/popup/popup.js#L761 Из-за этого, попап выглядит корректно только при первом открытии, а при последующих ломается.

2) В методе ``_getUIDialogExtraClass`` использована некорректная регулярка ``/\w+\_(?!_)/`` (https://github.com/yandex-ui/nanoislands/blob/master/blocks/popup/popup.js#L462) — она заматчится и на элемент без модификатора, чего, судя по комментариям, хотелось избежать. Пример:
````javascript
'block__elem'.split(/\w+\_(?!_)/)
["", "elem"]
````
В итоге для попапа с классами ``block__elem`` и ``block__elem_mod`` будут сгенерированы два класса ``outer_elem`` и ``outer_mod``.

**Comment by i2r** [comment]
Регулярку можно исправить, например, на такую: ``[^_]_(?!_)/``
````javascript
'block__elem'.split(/[^_]_(?!_)/)
["block__elem"]
````
 
При её использовании могут получаться некорректные части, но она точно отдаёт модификатор последний модификатор и не матчится на элемент:
````javascript
'block__elem'.split(/[^_]_(?!_)/)
["block__elem"]

'block__elem_mod'.split(/[^_]_(?!_)/)
["block__ele", "mod"]
````

**Comment by vitkarpov** [comment]
v0.7.0
