### ISSUE TITLE
В обработчике события nb-changed чекбокса всегда одно и то же value

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/nanoislands#514]
В обработчике `nb-changed` метод `getValue` всегда возвращает `on`. Нужно иметь возможность получать актуальное состояние чекбокса — судя по тому, что название событие `changed` в прошедшем времени, то уже новое состояние (после переключения)

**Comment by alexeyten** [comment]
Вообще у чекбокса есть метод `isChecked`?

**Comment by vitkarpov** [comment]
Да, `getValue` не то
